# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_and_export do
    # add actions here: https://docs.fastlane.tools/actions
  ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "10"
  ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6" 
  ENV["MATCH_PASSWORD"] = "iossummer"
    increment_version_number(version_number: "1.2")

    gym
    release = firebase_app_distribution(
	
        testers: "o.frankiv@ukma.edu.ua",
        release_notes: "Firebase app distribution with fastlane",
	app: "1:880449920699:ios:b2b0c1b097612bad51139e"
    )
  end
  lane :take_screenshots do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "10"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6"
    snapshot
  end
end
